### ISSUE TITLE
PHP Notice:  Trying to get property of non-object

### ISSUE THREAD

**Issue by jayvardhan** [Sputznik/orbit-bundle#5]
Following are reported frequently: 

 PHP Notice:  Trying to get property of non-object in /var/www/wp-content/plugins/orbit-bundle/orbit-templates/class-orbit-templates.php on line 98

PHP Notice:  Trying to get property of non-object in /var/www/wp-content/plugins/orbit-bundle/orbit-templates/class-orbit-templates.php on line 171

**Comment by samvthom16** [comment]
@jayvardhan where is this reported from?

**Comment by jayvardhan** [comment]
YKA production server.
