### ISSUE TITLE
New templates required in orbit shortcode for post query grids

### ISSUE THREAD

**Issue by guneetnarula** [Sputznik/orbit-bundle#76]
@samvthom16 @psychome004 

We need new template styles for the orbit shortcode (for post query grids). The references are here: https://indiahousingreport.in/homepage/

See these sections: Opinion pieces, Technical reports, Data Tales (sticky), Featured resource (Sticky). These are categories of posts in the WP database.

**Comment by samvthom16** [comment]
https://github.com/Sputznik/orbit-bundle/blob/master/orbit-templates/orbit-shortcodes.php
